services:
  db:
    image: postgres:16
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: tp_contenedores
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql  
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tp-network

volumes:
  postgres_data:

networks:
  tp-network:
    driver: bridge
