# =======================
# Configuración del servidor
# =======================
server.port=8084
spring.application.name=ms-flota

# =======================
# Base de datos PostgreSQL
# =======================
spring.datasource.url=jdbc:postgresql://localhost:5432/logistica
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# Usá este para crear las tablas en desarrollo
spring.jpa.hibernate.ddl-auto=update

# Dialecto SQL y logging
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
