# ===============================
# 🔹 CONFIGURACIÓN GENERAL
# ===============================
spring.application.name=ms-rutas
server.port=8082

# ===============================
# 🔹 CONFIGURACIÓN DE BASE DE DATOS (PostgreSQL en Docker)
# ===============================
spring.datasource.url=jdbc:postgresql://db:5432/tp_contenedores
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# 🔹 CONFIGURACIÓN DE JPA / HIBERNATE
# ===============================
# Modo de validación: comprueba que las entidades coincidan con las tablas del schema.sql
spring.jpa.hibernate.ddl-auto=validate

# Dialecto específico de PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Mostrar SQL generados en consola
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# 🔹 LOGGING (para depurar SQL y JPA)
# ===============================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.springframework.orm.jpa=INFO


# Si ms-rutas necesita consultar ms-flota o ms-solicitudes
ms.flota.url=http://ms-flota:8085
ms.solicitudes.url=http://ms-solicitudes:8083
