# ===============================
# 🔹 CONFIGURACIÓN BÁSICA DEL MICROSERVICIO
# ===============================
spring.application.name=ms-solicitudes
server.port=8083

# ===============================
# 🔹 CONEXIÓN A BASE DE DATOS (PostgreSQL en Docker)
# ===============================
spring.datasource.url=jdbc:postgresql://db:5432/tp_contenedores
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# 🔹 CONFIGURACIÓN JPA / HIBERNATE
# ===============================
# Valida que las entidades coincidan con las tablas del schema.sql
spring.jpa.hibernate.ddl-auto=validate

# Dialecto de PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Mostrar consultas SQL en la consola
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# 🔹 OPCIONAL: LOGGING
# ===============================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.springframework.orm.jpa=INFO


# conexion con los otros ms
# Si ms-solicitudes necesita llamar a ms-flota o ms-rutas
# ajustar despues
ms.flota.url=http://ms-flota:8085
ms.rutas.url=http://ms-rutas:8082
